# Generated by Django 2.0.2 on 2018-03-07 06:01

import awesome_avatar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('being', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='avatar',
            field=awesome_avatar.fields.AvatarField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
