# Generated by Django 2.0.2 on 2018-03-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('being', '0002_auto_20180307_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='avatar',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='avatars/', width_field=100),
        ),
    ]
