# Generated by Django 2.0.2 on 2018-03-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('being', '0003_auto_20180307_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
