# Generated by Django 2.0.2 on 2018-03-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('being', '0004_auto_20180307_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceduser',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='avatar_thumbs'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
