# Generated by Django 2.0.3 on 2018-03-06 20:41

import being.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=500, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(being.models.getadmin), to=settings.AUTH_USER_MODEL),
        ),
    ]
