# Generated by Django 2.0.2 on 2018-03-04 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('md_file', models.FileField(blank=True, default=None, null=True, upload_to='announcements/')),
                ('github_url', models.URLField(blank=True, default=None, null=True)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('talk_date', models.DateTimeField(verbose_name='time')),
                ('status', models.IntegerField(choices=[(0, 'preparing'), (1, 'ready'), (2, 'finished'), (3, 'disqualified')], default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-talk_date'],
            },
        ),
    ]
