# Generated by Django 2.0.2 on 2018-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='location',
            field=models.CharField(default='北京海淀区中科院物理所M楼830对面玻璃房', max_length=200),
        ),
    ]
