# Generated by Django 2.0.3 on 2018-03-06 20:41

import being.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_talk_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='location',
            field=models.CharField(default='北京海淀区中科院物理所M楼830对面玻璃房(Opposite to Room 830 Building M, IOP CAS, BeiJing)', max_length=200),
        ),
        migrations.AlterField(
            model_name='talk',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(being.models.getadmin), to=settings.AUTH_USER_MODEL),
        ),
    ]
